### ISSUE TITLE
Cannot find module error

### ISSUE THREAD

**Issue by jamiegood** [pion/11LiveChat#6]
Hello 
I'm attempting to the the app. When I do 'go run main.go'
It returns the following error:

build command-line-arguments: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519

Thanks 
Jamie

**Comment by Sean-Der** [comment]
Hey @jamiegood 

You need to use Go 1.13 or greater to use Pion WebRTC. I think that is where the issue is coming from. If you update and are still having issues mind sharing version/host I can help debug.

**Comment by jinleileiking** [comment]
@jamiegood try latest code with newest golang :) Closed. Reopen if you want. And welcome to the SLACK

**Comment by jamiegood** [comment]
Yes it works with the newer Go version. Thanks all for the help.
